### ISSUE TITLE
iconsets as per angular-material demo site

### ISSUE THREAD

**Issue by MilosStanic** [planet-training/material-design-icons#4]
I've been unable to use iconsets as described on page https://material.angularjs.org/0.9.8/#/demo/material.components.icon

```
angular.module('appSvgIconSets', ['ngMaterial'])
  .controller('DemoCtrl', function($scope) {})
  .config(function($mdIconProvider) {
    $mdIconProvider
      .iconSet('social', 'img/icons/sets/social-icons.svg', 24)
      .defaultIconSet('img/icons/sets/core-icons.svg', 24);
  });
```

and then in html: 

```
<md-icon md-svg-icon="social:people" style="color: #00F;" class="s48"            aria-label="People Icon"></md-icon>
```

The only way I can use the package as described in README.md, and then in html: 

```
<md-icon md-svg-icon="content:ic_send_24px"></md-icon>
```

whereas I would like to be able to do: 

```
<md-icon md-svg-icon="content:send"></md-icon>
```

Is this package related, or am I doing something wrong?

Thanks

**Comment by dohomi** [comment]
Hi @MilosStanic 

First I think you are using the wrong path? `/packages/planettraining_material-design-icons/bower_components/material-design-icons/sprites/svg-sprite/svg-sprite-social.svg` is the correct path to the sprite folder. 

The prefixing of `ic_`and appendix of `_24px`is related to the sprites of the google icon sets, if you open the svg files in an editor you will find this in all images as the icon `ID`.

Maybe you are interested in using the fonts instead of the SVG images? We added https://github.com/planet-training/material-design-icons-font and using this in our current project.

**Comment by MilosStanic** [comment]
Hi @dohomi the path is correct, becaues if it weren't I would get no icons at all. 
I have to prefix them with `ic_` and append them with `_24px`, but I thought I was doing something wrong. If that is the proper way, then okay. 

Thanks anyway.

**Comment by dohomi** [comment]
@MilosStanic yes this naming is the correct way. But how I mentioned in the other post, consider using the `material-design-icon-font`package. There you have a very small html markup:

```
<md-icon>face</md-icon>
```
